import {
  Baby,
  Bell,
  CircleDollarSign,
  CircleHelp,
  Footprints,
  Globe2,
  Heart,
  Info,
  LogOut,
  Mail,
  MapPin,
  Package,
  Tag,
  TrendingUp,
  User,
  Zap,
} from 'lucide-react-native';

import type { DrawerMenuItemConfig } from '@/types/drawer';

export const drawerMenuItems = [
  {
    badge: 'UP TO 50% OFF',
    icon: Tag,
    id: 'sale',
    label: 'SALE',
    tone: 'brand',
  },
  {
    disclosure: 'expand',
    dividerBefore: true,
    icon: User,
    id: 'men',
    label: 'Men',
  },
  { disclosure: 'expand', icon: User, id: 'women', label: 'Women' },
  { disclosure: 'expand', icon: Baby, id: 'kids', label: 'Kids' },
  { disclosure: 'navigate', icon: Footprints, id: 'footwear', label: 'Footwear' },
  {
    badge: 'NEW',
    dividerBefore: true,
    icon: Zap,
    id: 'new-arrivals',
    label: 'New Arrivals',
  },
  { disclosure: 'navigate', icon: TrendingUp, id: 'trending', label: 'Trending Now' },
  { disclosure: 'navigate', icon: Globe2, id: 'brands', label: 'Brands' },
  { badge: '3', dividerBefore: true, icon: Heart, id: 'wishlist', label: 'Wishlist' },
  { disclosure: 'navigate', icon: Package, id: 'orders', label: 'Orders' },
  { disclosure: 'navigate', icon: User, id: 'account', label: 'My Account' },
  { badge: '2', icon: Bell, id: 'notifications', label: 'Notifications' },
  {
    disclosure: 'expand',
    dividerBefore: true,
    icon: MapPin,
    id: 'country',
    label: 'Country',
    value: 'UAE',
  },
  {
    disclosure: 'expand',
    icon: CircleDollarSign,
    id: 'currency',
    label: 'Currency',
    value: 'AED',
  },
  {
    disclosure: 'navigate',
    dividerBefore: true,
    icon: Info,
    id: 'about',
    inset: true,
    label: 'About Us',
    tone: 'muted',
  },
  {
    disclosure: 'navigate',
    icon: Mail,
    id: 'contact',
    inset: true,
    label: 'Contact Us',
    tone: 'muted',
  },
  {
    disclosure: 'navigate',
    icon: CircleHelp,
    id: 'help',
    inset: true,
    label: 'Help Center',
    tone: 'muted',
  },
  {
    dividerBefore: true,
    icon: LogOut,
    id: 'logout',
    label: 'Logout',
    tone: 'brand',
  },
] as const satisfies readonly DrawerMenuItemConfig[];
