export const routes = {
  about: '/about',
  category: '/category',
  contact: '/contact',
  deliveryAddress: '/delivery-address',
  orderSuccess: '/order-success',
  payment: '/payment',
  footwearCollection: '/footwear-collection',
  home: '/',
  kidsCollection: '/kids-collection',
  mensCollection: '/mens-collection',
  productDetail: '/product-detail',
  productFilters: '/product-filters',
  shoppingBag: '/shopping-bag',
  womensCollection: '/womens-collection',
} as const;
