export const layout = {
  bottomTabBarHeight: 64,
  categoryCardAspectRatio: 0.8,
  categoryCircleSize: 68,
  categoryGridPhoneColumns: 2,
  categoryGridTabletColumns: 4,
  productCardImageHeight: 190,
  productCardWidth: 192,
  productGridMinimumColumns: 2,
  promotionalBannerHeight: 176,
  drawerPromotionImageHeight: 90,
  drawerPromotionImageWidth: 100,
  sidebarDrawerWidth: 320,
  styleCardHeight: 144,
  styleCardWidth: 112,
  tabletBreakpoint: 600,
  brandLogo: {
    width: 126,
    height: 18,
  },
} as const;
