export const typography = {
  fontFamily: {
    regular: 'Manrope_400Regular',
    medium: 'Manrope_500Medium',
    semibold: 'Manrope_600SemiBold',
    bold: 'Manrope_700Bold',
    extrabold: 'Manrope_800ExtraBold',
    display: 'InstrumentSerif_400Regular',
  },
  display: { fontSize: 36, lineHeight: 40, fontWeight: '400' as const },
  heading: { fontSize: 28, lineHeight: 34, fontWeight: '700' as const },
  title: { fontSize: 20, lineHeight: 26, fontWeight: '700' as const },
  body: { fontSize: 16, lineHeight: 24, fontWeight: '400' as const },
  label: { fontSize: 14, lineHeight: 20, fontWeight: '600' as const },
  caption: { fontSize: 12, lineHeight: 16, fontWeight: '400' as const },
  detail: { fontSize: 10, lineHeight: 12, fontWeight: '400' as const },
  micro: { fontSize: 9, lineHeight: 12, fontWeight: '400' as const },
  badge: { fontSize: 8, lineHeight: 10, fontWeight: '700' as const },
  overline: { fontSize: 10, lineHeight: 12, fontWeight: '800' as const },
} as const;
