import emeraldVelvetMaxiGownImage from '@/assets/images/collections/emerald-velvet-maxi-gown.webp';
import floralGeorgetteWrapDressImage from '@/assets/images/collections/floral-georgette-wrap-dress.webp';
import goldSequinPartyDressImage from '@/assets/images/collections/gold-sequin-party-dress.webp';
import handloomLinenMidiDressImage from '@/assets/images/collections/handloom-linen-midi-dress.webp';
import mensSlimFitWoolBlazerImage from '@/assets/images/collections/mens-slim-fit-wool-blazer.webp';
import mensTailoredLinenTrousersImage from '@/assets/images/collections/mens-tailored-linen-trousers.webp';
import satinVNeckSlipDressImage from '@/assets/images/collections/satin-v-neck-slip-dress.jpg';
import sequinCocktailMidiDressImage from '@/assets/images/collections/sequin-cocktail-midi-dress.webp';
import type { ProductPreview } from '@/types/product';

export const allCollections = [
  {
    bestPrice: { amount: 62, currency: 'AED' },
    brand: 'AND',
    deliveryLabel: 'Delivery by Jul 23',
    discountPercentage: 20,
    id: 'and-floral-georgette-wrap-dress',
    image: floralGeorgetteWrapDressImage,
    imageAccessibilityLabel: 'Model wearing a floral georgette wrap dress',
    imageFit: 'cover',
    isFavorite: false,
    name: 'Floral Georgette Wrap Dress',
    price: { amount: 78, currency: 'AED' },
    rating: 4.2,
    reviewCount: 92,
  },
  {
    bestPrice: { amount: 76, currency: 'AED' },
    brand: 'FABINDIA',
    deliveryLabel: 'Delivery by Jul 30',
    discountPercentage: 20,
    id: 'fabindia-handloom-linen-midi-dress',
    image: handloomLinenMidiDressImage,
    imageAccessibilityLabel: 'Model wearing a handloom linen midi dress on a beach',
    imageFit: 'cover',
    isFavorite: false,
    name: 'Handloom Linen Midi Dress',
    price: { amount: 95, currency: 'AED' },
    rating: 4.9,
    reviewCount: 156,
  },
  {
    bestPrice: { amount: 119, currency: 'AED' },
    brand: 'RAYMOND',
    deliveryLabel: 'Delivery by Aug 02',
    discountPercentage: 20,
    id: 'raymond-mens-slim-fit-wool-blazer',
    image: mensSlimFitWoolBlazerImage,
    imageAccessibilityLabel: 'Navy slim fit wool blazer',
    imageFit: 'cover',
    isFavorite: false,
    name: 'Men’s Slim Fit Wool Blazer',
    price: { amount: 149, currency: 'AED' },
    rating: 4.3,
    reviewCount: 84,
  },
  {
    bestPrice: { amount: 71, currency: 'AED' },
    brand: 'MARKS & SPENCER',
    deliveryLabel: 'Delivery by Jul 27',
    discountPercentage: 20,
    id: 'marks-and-spencer-satin-v-neck-slip-dress',
    image: satinVNeckSlipDressImage,
    imageAccessibilityLabel: 'Model wearing a royal-blue satin V-neck slip dress',
    imageFit: 'cover',
    isFavorite: false,
    name: 'Satin V-Neck Slip Dress',
    price: { amount: 89, currency: 'AED' },
    rating: 4.4,
    reviewCount: 112,
  },
  {
    bestPrice: { amount: 55, currency: 'AED' },
    brand: 'PETER ENGLAND',
    deliveryLabel: 'Delivery by Jul 29',
    discountPercentage: 20,
    id: 'peter-england-mens-tailored-linen-trousers',
    image: mensTailoredLinenTrousersImage,
    imageAccessibilityLabel: 'Stack of men’s tailored linen trousers',
    imageFit: 'cover',
    isFavorite: false,
    name: 'Men’s Tailored Linen Trousers',
    price: { amount: 68, currency: 'AED' },
    rating: 4.1,
    reviewCount: 67,
  },
  {
    bestPrice: { amount: 100, currency: 'AED' },
    brand: 'BCBG',
    deliveryLabel: 'Delivery by Aug 06',
    discountPercentage: 20,
    id: 'bcbg-sequin-cocktail-midi-dress',
    image: sequinCocktailMidiDressImage,
    imageAccessibilityLabel: 'Model wearing a navy sequin cocktail dress',
    imageFit: 'cover',
    isFavorite: false,
    name: 'Sequin Cocktail Midi Dress',
    price: { amount: 125, currency: 'AED' },
    rating: 4.8,
    reviewCount: 93,
  },
  {
    bestPrice: { amount: 116, currency: 'AED' },
    brand: 'MICHAEL KORS',
    deliveryLabel: 'Delivery by Aug 08',
    discountPercentage: 20,
    id: 'michael-kors-gold-sequin-party-dress',
    image: goldSequinPartyDressImage,
    imageAccessibilityLabel: 'Model wearing a black and gold sequin party dress',
    imageFit: 'cover',
    isFavorite: false,
    name: 'Gold Sequin Party Dress',
    price: { amount: 145, currency: 'AED' },
    rating: 4.6,
    reviewCount: 203,
  },
  {
    bestPrice: { amount: 151, currency: 'AED' },
    brand: 'CALVIN KLEIN',
    deliveryLabel: 'Delivery by Aug 01',
    discountPercentage: 20,
    id: 'calvin-klein-emerald-velvet-maxi-gown',
    image: emeraldVelvetMaxiGownImage,
    imageAccessibilityLabel: 'Model wearing an emerald velvet maxi gown',
    imageFit: 'cover',
    isFavorite: false,
    name: 'Emerald Velvet Maxi Gown',
    price: { amount: 189, currency: 'AED' },
    rating: 4.7,
    reviewCount: 87,
  },
] as const satisfies readonly ProductPreview[];
